# Generated by Django 4.0.1 on 2022-02-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_actor_birth_date_alter_actor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='matn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='film.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='janr',
            field=models.CharField(choices=[('action', 'action'), ('drama', 'drama'), ('comedy', 'comedy')], max_length=12),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
